# Generated by Django 5.0.7 on 2024-07-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_sustainabilitymanagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='crop_pictures')),
                ('crop_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('planting_time', models.TextField()),
                ('fertilizer', models.TextField()),
                ('irrigation', models.TextField()),
                ('harvest', models.TextField()),
                ('cleaning', models.TextField()),
                ('storage', models.TextField()),
                ('transportation', models.TextField()),
                ('consumption', models.TextField()),
                ('end_of_life', models.TextField()),
            ],
        ),
    ]
