# Generated by Django 5.0.7 on 2024-07-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='photo',
            new_name='crop_image',
        ),
    ]
