# Generated by Django 5.0.7 on 2024-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_photo_crop_crop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropFertilizerPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(choices=[('Kagarama', 'Kagarama'), ('Nyakabanda', 'Nyakabanda'), ('Musha', 'Musha'), ('Akabare', 'Akabare'), ('Nyabisindu', 'Nyabisindu'), ('Budahanda', 'Budahanda')], max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('nitrogen', models.IntegerField(default=0)),
                ('phosphorus', models.IntegerField(default=0)),
                ('potassium', models.IntegerField(default=0)),
                ('ph', models.FloatField()),
                ('rainfall', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('predicted_crop', models.CharField(max_length=100)),
                ('predicted_fertilizer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
