# Generated by Django 5.0.7 on 2024-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_cropfertilizerpredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropfertilizerpredict',
            name='nitrogen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cropfertilizerpredict',
            name='phosphorus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cropfertilizerpredict',
            name='potassium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cropfertilizerpredict',
            name='rainfall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cropfertilizerpredict',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
