# Generated by Django 5.0.7 on 2024-08-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropfertilizerpredict',
            old_name='village',
            new_name='cell',
        ),
    ]
