# Generated by Django 5.0.7 on 2024-07-23 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('title', models.CharField(blank=True, default='farmer', max_length=50, null=True)),
                ('province', models.CharField(blank=True, choices=[('west', 'Western Province'), ('east', 'Eastern Province'), ('south', 'South Province'), ('north', 'North Province'), ('kigali', 'Kigali')], max_length=20, null=True)),
                ('district', models.CharField(blank=True, choices=[('karongi', 'Karongi'), ('rusizi', 'Rusizi'), ('rutsiro', 'Rutsiro'), ('nyamasheke', 'Nyamasheke'), ('ngororero', 'Ngororero'), ('nyabihu', 'Nyabihu'), ('rubavu', 'Rubavu')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
