# Generated by Django 5.0.7 on 2024-07-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
    ]
