# Generated by Django 5.0.7 on 2024-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='title',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('admin', 'Admin')], default='farmer', max_length=50, null=True),
        ),
    ]
