# Generated by Django 5.0.7 on 2024-07-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='title',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin')], default='farmer', max_length=50),
        ),
    ]
