# Generated by Django 5.0.7 on 2024-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_userprofiles_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofiles",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("farmer", "Farmer"), ("admin", "Admin")],
                default="farmer",
                max_length=50,
                null=True,
            ),
        ),
    ]
