# Generated by Django 5.0.7 on 2024-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofiles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='sector',
            field=models.CharField(default='Musha Sector', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='village',
            field=models.CharField(blank=True, choices=[('Kagarama', 'Kagarama'), ('Nyakabanda', 'Nyakabanda'), ('Musha', 'Musha'), ('Akabare', 'Akabare'), ('Nyabisindu', 'Nyabisindu'), ('Budahanda', 'Budahanda')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='district',
            field=models.CharField(blank=True, default='Rwamagana', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='province',
            field=models.CharField(blank=True, default='Eastern', max_length=20, null=True),
        ),
    ]
