# Generated by Django 5.0.7 on 2024-08-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofiles_sector_userprofiles_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='title',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('admin', 'Admin'), ('rab', 'RAB')], default='farmer', max_length=50, null=True),
        ),
    ]
