# Generated by Django 5.0.7 on 2024-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofiles_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='village',
            new_name='cell',
        ),
    ]
