# Generated by Django 5.0.7 on 2024-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_yieldpredictions_is_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldpredictions',
            name='yield_pred_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
