# Generated by Django 5.0.7 on 2024-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0003_alter_yieldpredictions_yield_pred_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yieldpredictions',
            options={'verbose_name_plural': 'YieldPredictions'},
        ),
    ]
